version: '3.8'

services:
    valheim-server:
        image: toneoyay/valhalla:latest
        ports:
            - '2456:2456/udp'
            - '2456:2456/tcp'
            - '2457:2457/udp'
        volumes:
            - ./saves/:/home/steam/valheim-dserver/save/
        environment:
            - VALHEIM_NAME=Til Valhalla
            - VALHEIM_PASSWORD=password
        restart: always
